// Code generated by Prismic. DO NOT EDIT.

import AlternateGrid from "./AlternateGrid";
import CallToAction from "./CallToAction";
import CustomerLogos from "./CustomerLogos";
import Hero from "./Hero";
import HeroSectionWithImage from "./HeroSectionWithImage";
import RichText from "./RichText";

export const components = {
	alternate_grid: AlternateGrid,
	call_to_action: CallToAction,
	customer_logos: CustomerLogos,
	hero: Hero,
	hero_section_with_image: HeroSectionWithImage,
	rich_text: RichText
};